### ISSUE TITLE
Demo failure

### ISSUE THREAD

**Issue by rapture216** [Equidamoid/pyconz#2]
I'm trying to use this code to play with my IoT devices without deCONZ, but your demo script is failing. It looks like the zigpy v0.1.0 library is missing some commands/message types, but there's no other version available. Do you have an updated zigpy that you're using, or could you show me how you set up the 0x8031 response? (I've tried a few things, but each time either demo or zigpy complains about my format).
-r

**Comment by Equidamoid** [comment]
Oh, indeed, I have patched zigpy. Will put it somewhere in coming days.

**Comment by rapture216** [comment]
Awesome, thank you.

**Comment by Equidamoid** [comment]
Oh, nice, they already implemented the missing feature. Will try to use it...

**Comment by Equidamoid** [comment]
Done, 140a788c9efdf28f68338d759785b64dca99d7d3, please pull and try again =)

**Comment by Equidamoid** [comment]
(closed accidentally)

**Comment by rapture216** [comment]
Hey, hope you weren't waiting on me to close this. Sorry. Yes, that seems to have fixed the issue I was having with the demo.
